[versions]
agp = "8.13.2"
kotlin = "2.3.0"
work = "2.11.0"
idgenerator = "1.0.6"
network = "1.0.4"

[libraries]
androidx-work = {module = "androidx.work:work-runtime-ktx",version.ref = "work"}
idgenerator = {module = "com.github.yitter:yitter-idgenerator",version.ref = "idgenerator"}
network = {module = "com.github.Caleb-Rainbow:Ktor-Network",version.ref = "network"}

[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
